[package]
name = "curl_matrix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1"
nalgebra = "0.32"
rpi-led-panel = "0.2.0"
rand = "0.8.5"

[dev-dependencies]
embedded-graphics = "0.7.1"