[build]
target = "aarch64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-g++"
rustflags = [
    "-L", "/usr/lib/gcc-cross/aarch64-linux-gnu/15",
    "-L", "/usr/aarch64-linux-gnu/lib",
]

[env]
CC_aarch64-unknown-linux-gnu = "aarch64-linux-gnu-gcc"
CXX_aarch64-unknown-linux-gnu = "aarch64-linux-gnu-g++"